server:
  port: 8090

spring:
  application:
    name: mscv-student

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/studentdb
    username: root
    password: AdminDB123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/