server:
  port: 8080

eureka:
  client:
    register-with-eureka: false



spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/students/**
          - id: courses
            uri: http://localhost:9090
            predicates:
              - Path=/api/v1/courses/**
